#!/usr/bin/env node
const readline = require('readline')
const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')
let version = process.argv[2]

const packageJson = require(path.join(process.cwd(), './package.json'))

if (!packageJson.version) {
  console.log('No version found in package.json')
  return
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
})

if (version && !isValidVersion(version)) {
  console.log('Invalid version: ', version)
  console.log('Current version: ', packageJson.version)
  return
}

if (version && packageJson.version === version) {
  console.log('Version is already set to ', version)
  return
}

if (!version) {
  console.log('Current version: ', packageJson.version)
  version = incrementPatchVersion(packageJson.version)
  rl.question(`Do you want to increment the version to ${version}? (y/n) `, (answer) => {
    if (answer === 'y') {
      publish(version)
    } else {
      console.log('Aborted')
    }
    rl.close()
  })

  return
} else {
  publish(version)
}

function isValidVersion(version) {
  return /^(\d+)\.(\d+)\.(\d+)(?:-([\w-]+(?:\.[\w-]+)*))?(?:\+([\w-]+(?:\.[\w-]+)*))?$/.test(version)
}

function incrementPatchVersion(version) {
  const parts = version.split('.')
  const patch = parseInt(parts[2]) + 1
  return `${parts[0]}.${parts[1]}.${patch}`
}

function run(cmd) {
  console.log(cmd)
  const out = execSync(cmd)
  console.log(out.toString())
}

function publish(version) {
  packageJson.version = version
  fs.writeFileSync('package.json', JSON.stringify(packageJson, null, 2))

  run('git add package.json')
  run(`git commit -m "Bump version to ${version}"`)
  run(`git tag v${version}`)
  run('git push')
  run(`git push --tags`)
  
  rl.question(`Do you want to create a release on GitHub? (y/n) `, (answer) => {
    if (answer === 'y') {
      let notesArg = '--generate-notes'
      rl.question(`Enter notes for the release (optional): `, (notes) => {
        if (notes.trim() !== '') {
          notesArg = `--notes "${notes}"`
        }
        rl.close()
      })
    run(`gh release create v${version} --title "v${version}" ${notesArg} --latest`)
    } else {
      console.log('Aborted')
    }
  })

  run ('npm publish')
}


